### ISSUE TITLE
StakeRegistry.modifyStrategyParams does NOT enforce the same conditions on multipliers enforced by `addStrategies`

### ISSUE THREAD

**Issue by wadealexc** [Layr-Labs/eigenlayer-middleware#128]
`_addStrategyParams` requires that multipliers are nonzero:

https://github.com/Layr-Labs/eigenlayer-middleware/blob/ebe657e1167e59dc7959dfe11c8194b72bf9a347/src/StakeRegistry.sol#L416-L419

`modifyStrategyParams` does not have this check:

https://github.com/Layr-Labs/eigenlayer-middleware/blob/ebe657e1167e59dc7959dfe11c8194b72bf9a347/src/StakeRegistry.sol#L269-L273

Not a huge deal, but something we should consider changing for consistency.

**Comment by ChaoticWalrus** [comment]
My thoughts here:
I think this inconsistency is likely acceptable, but I do have a preference for consistency in general.
In this particular instance, I can see reducing a strategy multiplier to zero as perhaps a temporary measure / taken instead of removing a strategy from the list (e.g. in the case of an apparent infinite mint bug in the underlying token), while I don't see any case in which you would want to _add_ a strategy with zero multiplier. However, it does feel like the correct action would be to remove the strategy from consideration, rather than reducing its multiplier to zero :|
I'm cool with adding the check to the `modifyStrategyParams` function -- maybe the revert message could just helpfully instruct to use the `removeStrategies` (or whatever its called) function instead?

**Comment by wadealexc** [comment]
closing this as it's low prio and i dont have time to address it before audits start
