### ISSUE TITLE
fix: pinned eigenlayer-contracts version is broken

### ISSUE THREAD

**Issue by taturosati** [Layr-Labs/eigenlayer-middleware#229]
**Describe the bug**
Checked out commit of eigenlayer-contracts submodule script `M2_Deploy_From_Scratch.s.sol` does not work. The issue is it references old folder `script/testing` in line 103. This has been fixed on commit [41b4361](https://github.com/Layr-Labs/eigenlayer-contracts/commit/41b4361caab11dcf7ecd92a7bcef3dba73c6f12e) on eigenlayer-contracts repo.

**To Reproduce**
1. Clone eigenlayer-middleware repo on dev branch or release tags [v0.1.3-mainnet-m2+pragma-change](https://github.com/Layr-Labs/eigenlayer-middleware/tree/v0.1.3-mainnet-m2%2Bpragma-change) or [v0.1.3-mainnet-m2](https://github.com/Layr-Labs/eigenlayer-middleware/tree/v0.1.3-mainnet-m2/docs)
2. Start anvil
3. Enter lib/eigenlayer-contracts
4. Run `forge script script/testing/M2_Deploy_From_Scratch.s.sol --rpc-url $RPC_URL --private-key $PRIVATE_KEY --broadcast --sig "run(string memory configFile)" -- M2_deploy_from_scratch.anvil.config.json`
5. See error "File not found"

**Expected behavior**
Eigen Layer contracts should be deployed to anvil

**Environment**
Enter important environment info needed to reproduce the bug. 
 - dev branch
 - v0.1.3-mainnet-m2
 - v0.1.3-mainnet-m2+pragma-change

**Comment by 0xdfinity** [comment]
## Bug Report: `M2_Deploy_From_Scratch.s.sol` Script Not Working

### Steps to Reproduce:
1. Clone the **eigenlayer-middleware** repository from the **dev** branch or use release tags (e.g., `v0.1.3-mainnet-m2+pragma-change` or `v0.1.3-mainnet-m2`).
2. Start Anvil.
3. Navigate to `lib/eigenlayer-contracts`.
4. Execute the following command:
   ```
   forge script script/testing/M2_Deploy_From_Scratch.s.sol --rpc-url $RPC_URL --private-key $PRIVATE_KEY --broadcast --sig "run(string memory configFile)" -- M2_deploy_from_scratch.anvil.config.json
   ```
5. Observe the error message: "File not found."

Expected Behavior:
The Eigen Layer contracts should be successfully deployed to Anvil without encountering any file-related issues.

### Environment:
- Branch: **dev**
- Release Tags Tested: **v0.1.3-mainnet-m2**, **v0.1.3-mainnet-m2+pragma-change**

### Suggested Fix:
1. Update line 103 in the `M2_Deploy_From_Scratch.s.sol` script to reference the correct folder path.
2. Verify that the script executes without errors.

**Comment by stevennevins** [comment]
Just closing as this is out of date now
